[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/juego/*"
  to = "/Game/keepYourSheep/build/index.html"
  status = 200
  force = true